import { Pool, type PoolClient } from "pg";
import type { Actor } from "@/lib/jmr-core";

export type D1Result<T = Record<string, unknown>> = {
  results?: T[];
  meta?: { changes?: number };
};

type Prepared = {
  sql: string;
  values: unknown[];
};

export type D1Statement = {
  bind(...values: unknown[]): D1Statement;
  first<T = Record<string, unknown>>(): Promise<T | null>;
  all<T = Record<string, unknown>>(): Promise<{ results: T[] }>;
  run<T = Record<string, unknown>>(): Promise<D1Result<T>>;
  _prepared(): Prepared;
};

export type D1Database = {
  prepare(query: string): D1Statement;
  batch<T = Record<string, unknown>>(statements: D1Statement[]): Promise<D1Result<T>[]>;
};

type RuntimeEnv = {
  DATABASE_URL?: string;
  JMR_APP_PIN?: string;
  JMR_ADMIN_USERNAME?: string;
  JMR_ADMIN_PASSWORD?: string;
  JMR_SESSION_SECRET?: string;
  APP_ORIGIN?: string;
};

export function runtimeEnv(): RuntimeEnv {
  return process.env;
}

let pool: Pool | null = null;
let initialized: Promise<void> | null = null;

function getPool(): Pool {
  const url = runtimeEnv().DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is required for the Hostinger PostgreSQL runtime.");
  if (!pool) {
    pool = new Pool({
      connectionString: url,
      max: 8,
      idleTimeoutMillis: 30_000,
      connectionTimeoutMillis: 10_000,
      ssl: url.includes("localhost") ? false : { rejectUnauthorized: false },
    });
  }
  return pool;
}

function normalizeSql(sql: string): string {
  let result = sql.trim();
  let ignoreConflict = false;
  if (/^INSERT\s+OR\s+IGNORE\s+INTO\s+/i.test(result)) {
    result = result.replace(/^INSERT\s+OR\s+IGNORE\s+INTO\s+/i, "INSERT INTO ");
    ignoreConflict = true;
  }
  let index = 0;
  result = result.replace(/\?/g, () => `$${++index}`);
  if (ignoreConflict && !/\bON\s+CONFLICT\b/i.test(result)) result += " ON CONFLICT DO NOTHING";
  return result;
}

async function queryOnClient<T = Record<string, unknown>>(client: PoolClient, statement: Prepared): Promise<D1Result<T>> {
  const result = await client.query(normalizeSql(statement.sql), statement.values);
  return { results: result.rows as T[], meta: { changes: result.rowCount ?? 0 } };
}

async function withClient<T>(callback: (client: PoolClient) => Promise<T>): Promise<T> {
  const client = await getPool().connect();
  try {
    await client.query("SET search_path TO jmr, public");
    return await callback(client);
  } finally {
    client.release();
  }
}

class Statement implements D1Statement {
  constructor(private sql: string, private values: unknown[] = []) {}
  bind(...values: unknown[]): D1Statement { return new Statement(this.sql, values); }
  _prepared(): Prepared { return { sql: this.sql, values: this.values }; }
  async first<T = Record<string, unknown>>(): Promise<T | null> {
    return withClient(async client => {
      const result = await queryOnClient<T>(client, this._prepared());
      return result.results?.[0] ?? null;
    });
  }
  async all<T = Record<string, unknown>>(): Promise<{ results: T[] }> {
    return withClient(async client => ({ results: (await queryOnClient<T>(client, this._prepared())).results ?? [] }));
  }
  async run<T = Record<string, unknown>>(): Promise<D1Result<T>> {
    return withClient(client => queryOnClient<T>(client, this._prepared()));
  }
}

const database: D1Database = {
  prepare(query: string) { return new Statement(query); },
  async batch<T = Record<string, unknown>>(statements: D1Statement[]): Promise<D1Result<T>[]> {
    return withClient(async client => {
      await client.query("BEGIN");
      try {
        const results: D1Result<T>[] = [];
        for (const statement of statements) results.push(await queryOnClient<T>(client, statement._prepared()));
        await client.query("COMMIT");
        return results;
      } catch (error) {
        await client.query("ROLLBACK");
        throw error;
      }
    });
  },
};

export function getDb(): D1Database {
  return database;
}

const schema = [
  `CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_section TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT '', owner TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '',
    occupant TEXT NOT NULL DEFAULT '', occupant_number TEXT NOT NULL DEFAULT '', rent_start TEXT NOT NULL DEFAULT '',
    rent_end TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), created_at TEXT NOT NULL DEFAULT (now()::text)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_jmr_departments_meter_section_nocase ON departments ((lower(trim(meter_section))))`,
  `CREATE TABLE IF NOT EXISTS monthly_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, month TEXT NOT NULL, department_id BIGINT NOT NULL REFERENCES departments(id),
    meter_fee DOUBLE PRECISION NOT NULL DEFAULT 0, kilo_price DOUBLE PRECISION NOT NULL DEFAULT 0, rent DOUBLE PRECISION NOT NULL DEFAULT 0,
    services DOUBLE PRECISION NOT NULL DEFAULT 0, previous_reading DOUBLE PRECISION NOT NULL DEFAULT 0, current_reading DOUBLE PRECISION NOT NULL DEFAULT 0,
    locked INTEGER NOT NULL DEFAULT 0 CHECK(locked IN (0,1)), updated_at TEXT NOT NULL DEFAULT (now()::text), UNIQUE(month, department_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_monthly_records_month ON monthly_records(month)`,
  `CREATE INDEX IF NOT EXISTS idx_monthly_records_department_month ON monthly_records(department_id, month)`,
  `CREATE TABLE IF NOT EXISTS month_status (
    month TEXT PRIMARY KEY NOT NULL, locked INTEGER NOT NULL DEFAULT 0 CHECK(locked IN (0,1)), approved_at TEXT, approved_by TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS record_meta (
    record_id BIGINT PRIMARY KEY NOT NULL REFERENCES monthly_records(id) ON DELETE CASCADE,
    confirmed INTEGER NOT NULL DEFAULT 0 CHECK(confirmed IN (0,1)), revision INTEGER NOT NULL DEFAULT 1 CHECK(revision > 0), write_token TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS monthly_snapshots (
    record_id BIGINT PRIMARY KEY NOT NULL REFERENCES monthly_records(id) ON DELETE CASCADE, meter_section TEXT NOT NULL, category TEXT NOT NULL DEFAULT '',
    owner TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '', occupant TEXT NOT NULL DEFAULT '', occupant_number TEXT NOT NULL DEFAULT '',
    rent_start TEXT NOT NULL DEFAULT '', rent_end TEXT NOT NULL DEFAULT ''
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY NOT NULL, username TEXT NOT NULL, name TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('owner','accountant','viewer')), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
    password_hash TEXT NOT NULL, session_version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT (now()::text)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_jmr_users_username_nocase ON users ((lower(username)))`,
  `CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, session_version INTEGER NOT NULL, expires_at BIGINT NOT NULL, created_at BIGINT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at)`,
  `CREATE TABLE IF NOT EXISTS payments (
    id TEXT PRIMARY KEY NOT NULL, record_id BIGINT NOT NULL REFERENCES monthly_records(id), kind TEXT NOT NULL CHECK(kind IN ('rent','electricity')),
    amount DOUBLE PRECISION NOT NULL CHECK(amount > 0), paid_at TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', received_by TEXT NOT NULL,
    created_at TEXT NOT NULL, voided_at TEXT, voided_by TEXT, void_reason TEXT, request_id TEXT NOT NULL UNIQUE
  )`,
  `CREATE INDEX IF NOT EXISTS idx_payments_record_id ON payments(record_id)`,
  `CREATE TABLE IF NOT EXISTS audit_log (
    id TEXT PRIMARY KEY NOT NULL, created_at TEXT NOT NULL, user_id TEXT NOT NULL, actor_name TEXT NOT NULL, action TEXT NOT NULL, detail TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS auth_login_rate_limits (
    client_key TEXT PRIMARY KEY NOT NULL, failure_count INTEGER NOT NULL DEFAULT 0, window_started_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_auth_login_rate_limits_updated_at ON auth_login_rate_limits(updated_at)`,
];

async function performInit(): Promise<void> {
  const db = getDb();
  await db.batch(schema.map(sql => db.prepare(sql)));
  await db.batch([
    db.prepare(`INSERT OR IGNORE INTO month_status (month, locked)
      SELECT month, MIN(locked) FROM monthly_records GROUP BY month`),
    db.prepare(`INSERT OR IGNORE INTO record_meta (record_id, confirmed, revision)
      SELECT id, CASE WHEN locked = 1 THEN 1 ELSE 0 END, 1 FROM monthly_records`),
    db.prepare(`INSERT OR IGNORE INTO monthly_snapshots (
      record_id, meter_section, category, owner, phone, occupant, occupant_number, rent_start, rent_end
    ) SELECT r.id, d.meter_section, d.category, d.owner, d.phone, d.occupant, d.occupant_number, d.rent_start, d.rent_end
      FROM monthly_records r JOIN departments d ON d.id = r.department_id`),
    db.prepare(`UPDATE monthly_records SET locked = COALESCE(
      (SELECT locked FROM month_status m WHERE m.month = monthly_records.month), locked
    )`),
    db.prepare("DELETE FROM sessions WHERE expires_at < ?").bind(Date.now()),
  ]);
}

export async function initDatabase(): Promise<void> {
  initialized ??= performInit().catch(error => { initialized = null; throw error; });
  await initialized;
}

export async function writeAudit(actor: Actor, action: string, detail: string): Promise<void> {
  const db = getDb();
  await db.prepare(`INSERT INTO audit_log (id, created_at, user_id, actor_name, action, detail)
    VALUES (?, ?, ?, ?, ?, ?)`)
    .bind(crypto.randomUUID(), new Date().toISOString(), actor.id, actor.name, action, detail)
    .run();
}

export async function usersCount(): Promise<number> {
  const row = await getDb().prepare("SELECT COUNT(*) AS count FROM users").first<{ count: number }>();
  return Number(row?.count ?? 0);
}
