-- Tables the app expects in the jmr schema (created on Hostinger by the Supabase migration).
-- Used only by tests/postgres.test.mjs.
CREATE TABLE IF NOT EXISTS departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_section TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT '', owner TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '',
    occupant TEXT NOT NULL DEFAULT '', occupant_number TEXT NOT NULL DEFAULT '', rent_start TEXT NOT NULL DEFAULT '',
    rent_end TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), created_at TEXT NOT NULL DEFAULT (now()::text)
  );
CREATE UNIQUE INDEX IF NOT EXISTS idx_jmr_departments_meter_section_nocase ON departments ((lower(trim(meter_section))));
CREATE TABLE IF NOT EXISTS monthly_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, month TEXT NOT NULL, department_id INTEGER NOT NULL REFERENCES departments(id),
    meter_fee DOUBLE PRECISION NOT NULL DEFAULT 0, kilo_price DOUBLE PRECISION NOT NULL DEFAULT 0, rent DOUBLE PRECISION NOT NULL DEFAULT 0,
    services DOUBLE PRECISION NOT NULL DEFAULT 0, previous_reading DOUBLE PRECISION NOT NULL DEFAULT 0, current_reading DOUBLE PRECISION NOT NULL DEFAULT 0,
    locked INTEGER NOT NULL DEFAULT 0 CHECK(locked IN (0,1)), updated_at TEXT NOT NULL DEFAULT (now()::text), UNIQUE(month, department_id)
  );
CREATE INDEX IF NOT EXISTS idx_monthly_records_month ON monthly_records(month);
CREATE INDEX IF NOT EXISTS idx_monthly_records_department_month ON monthly_records(department_id, month);
CREATE TABLE IF NOT EXISTS month_status (
    month TEXT PRIMARY KEY NOT NULL, locked INTEGER NOT NULL DEFAULT 0 CHECK(locked IN (0,1)), approved_at TEXT, approved_by TEXT
  );
CREATE TABLE IF NOT EXISTS record_meta (
    record_id INTEGER PRIMARY KEY NOT NULL REFERENCES monthly_records(id) ON DELETE CASCADE,
    confirmed INTEGER NOT NULL DEFAULT 0 CHECK(confirmed IN (0,1)), revision INTEGER NOT NULL DEFAULT 1 CHECK(revision > 0), write_token TEXT
  );
CREATE TABLE IF NOT EXISTS monthly_snapshots (
    record_id INTEGER PRIMARY KEY NOT NULL REFERENCES monthly_records(id) ON DELETE CASCADE, meter_section TEXT NOT NULL, category TEXT NOT NULL DEFAULT '',
    owner TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '', occupant TEXT NOT NULL DEFAULT '', occupant_number TEXT NOT NULL DEFAULT '',
    rent_start TEXT NOT NULL DEFAULT '', rent_end TEXT NOT NULL DEFAULT ''
  );
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY NOT NULL, username TEXT NOT NULL, name TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('owner','accountant','viewer')), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
    password_hash TEXT NOT NULL, session_version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT (now()::text)
  );
CREATE UNIQUE INDEX IF NOT EXISTS idx_jmr_users_username_nocase ON users ((lower(username)));
CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL, session_version INTEGER NOT NULL, expires_at BIGINT NOT NULL, created_at BIGINT NOT NULL, client_fingerprint TEXT
  );
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS payments (
    id TEXT PRIMARY KEY NOT NULL, record_id INTEGER NOT NULL REFERENCES monthly_records(id), kind TEXT NOT NULL CHECK(kind IN ('rent','electricity')),
    amount DOUBLE PRECISION NOT NULL CHECK(amount > 0), paid_at TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', received_by TEXT NOT NULL,
    created_at TEXT NOT NULL, voided_at TEXT, voided_by TEXT, void_reason TEXT, request_id TEXT NOT NULL UNIQUE
  );
CREATE INDEX IF NOT EXISTS idx_payments_record_id ON payments(record_id);
CREATE TABLE IF NOT EXISTS audit_log (
    id TEXT PRIMARY KEY NOT NULL, created_at TEXT NOT NULL, user_id TEXT NOT NULL, actor_name TEXT NOT NULL, action TEXT NOT NULL, detail TEXT NOT NULL
  );
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at DESC);
CREATE TABLE IF NOT EXISTS auth_login_rate_limits (
    client_key TEXT PRIMARY KEY NOT NULL, failure_count INTEGER NOT NULL DEFAULT 0, window_started_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
  );
CREATE INDEX IF NOT EXISTS idx_auth_login_rate_limits_updated_at ON auth_login_rate_limits(updated_at);
